# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# syntax=docker/dockerfile:1
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy project files
COPY package.json package-lock.json tsconfig.json ./
COPY src ./src

# Install dependencies without running prepare script
RUN npm install --ignore-scripts

# Build the project
RUN npm run build

# Final stage
FROM node:lts-alpine
WORKDIR /app

# Copy build artifacts and dependencies
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY package.json ./

# Create a symlink for CLI
RUN chmod +x build/index.js \
    && ln -s /app/build/index.js /usr/local/bin/homeassistant-server

ENTRYPOINT ["homeassistant-server"]
